### ISSUE TITLE
Cellranger vs STAR pipeline

### ISSUE THREAD

**Issue by dkeitley** [fw262/TAR-scRNA-seq#7]
Hi Michael, 

I managed to get the original pipeline working on my dataset, but I've since noticed that you've updated the workflow to accept alignment files from cellranger. Since I'm using 10X data, I was just wondering whether this means I should now re-run the pipeline and if so, whether there are any steps I can avoid repeating? I'm working with a large number of samples so am wondering what the implications are if I keep with the results from the original STAR alignment and integrated the non-annotated TARs with the cellranger counts from the annotated genes...?

Best wishes,

Dan

**Comment by fw262** [comment]
Hi Dan,

I'm glad to hear the pipeline worked on your dataset. There shouldn't be major differences with the cellranger output update. In the updated cellranger output pipeline, TARs are uncovered from the cellranger generated alignment file which is generated using STAR. The original pipeline generates the alignment file using STAR directly. There should not be any major differences since both pipeline use STAR as the aligner.

Best,
Michael
